### PR TITLE
Don't fail build on CNF errors

### PR DESCRIPTION
**Pull request by KostyaSha**
https://issues.jenkins-ci.org/browse/JENKINS-53593
@olivergondza @vjuranek  i can't revert style change if needed, seems initial file was to messy and ide formated it
related https://github.com/jenkinsci/jenkins/pull/3627

### CODE REVIEW

**Comment by olivergondza** [comment]
Note this plugin is unmaintained, this is the first time I hear it exists. The change looks good to me, though.

**Comment by olivergondza** [comment]
@KostyaSha, care to become a maintainer? :wink:

**Comment by vjuranek** [comment]
Merged, thanks @KostyaSha . I have some issues with the relase and no time to solve it right now, will release it later today or tomorrow

**Comment by vjuranek** [comment]
and yes, if you want to become a maintainer, you are very welcome @KostyaSha

**Comment by vjuranek** [comment]
ok, as plugin is very old nad have no developer infomation, it's not set in jenkins-infra/repository-permissions-updater ... will send a PR laet today and once merged, I'll release it

**Comment by vjuranek** [comment]
released as `1.1`

**Comment by KostyaSha** [comment]
@olivergondza default killer with default signal doesn't kill all processes, so you can have orphaned processes on linux slaves (you can scan existing slaves with groovy script). Though it not an issue for container one-shot builds.
@vjuranek thanks

**Pull request merged**
